sudo: false
language: java
before_install: echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc
jdk: oraclejdk8
branches:
  only:
    - develop
install:  mvn versions:set
script: mvn deploy