# Duke Encounters
duke:
  encounters:
    latest-amount: 10
    password-strength: 10

# Session
server:
  session:
    timeout: 1800

spring:
  h2:
    console:
      path: /admin/h2-console
  resources:
    chain:
      enabled: true
  mvc:
    favicon:
      enabled: false

# Actuator
management:
  context-path: /admin
  security:
    enabled: true

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin

info:
  application:
    env: Production