# Duke Encounters
encounters:
  latest:
    amount: 10

# Session
server:
  session:
    timeout: 1800

spring:
  resources:
    chain:
      enabled: true
  mvc:
    favicon:
      enabled: false

# GitHub
github:
  client:
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

# Actuator
management:
  context-path: /admin
  security:
    enabled: true

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin

info:
  application:
    metadata: Duke Encounters
    artifactId: ${project.artifactId}
    groupId: ${project.groupId}
    version: ${project.version}

# Logging
logging:
  path: /var/logs/
  file: duke-encounters:log
  level:
    root: WARN
    org.springframework: ERROR
    org.hibernate: ERROR
    org.thymeleaf: ERROR